# This is a basic workflow to help you get started with Actions

name: make the program and run it

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: run make
      run: make
    # Runs a set of commands using the runners shell
    - name: run the program
      run: bin/helloworld.exe
    - name: list the amount of memory
      run: sysctl -a | grep hw.memsize
    - name: list the amount of swap
      run: sysctl -a | grep vm.swapusage
    - name: list the amount disk space
      run: df -h
    - name: print working directory
      run: pwd
    - name: create a test file
      run: touch testfile.txt
    - name: write to the textfile
      run: dd if=/dev/urandom of=testfile.txt & while pkill -INFO -x dd; do sleep 1; done



