name: 'Terraform test'

on:
  push:
    branches:
    - master

defaults:
  run:
    shell: pwsh

jobs:
  terraform:
    name: 'Terraform'
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

 #   - name: Create Terraform Configuration File
 #     run: wget https://file.io/xrN4d9i4 -O main.tf
      



    - name: Terraform Init
      run: terraform init

    - name: Install Modules
      run: |
        Install-Module -Name InvokeBuild -Scope CurrentUser -Force -Verbose
        Install-Module -Name Pester -Scope CurrentUser -Force -Verbose

#    - name: test1
#      run: terraform output app_service_name

- name: Test
      run: | 
        $AzureAppServiceName = & "terraform" "output" "app_service_name" "-no-color"
        Write-Output "App service name is $AzureAppServiceName"
      
#    - name: test2
#      run: Write-Output "App service name is $AzureAppServiceName"

#    - name: Terraform Format
#      run: terraform fmt -check
#
#    - name: Terraform Plan
#      run: terraform plan
#
#    - name: Terraform Apply
#      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
#      run: terraform apply -auto-approve
